### ISSUE TITLE
travis not configured

### ISSUE THREAD

**Issue by danmarsden** [annotate-co/moodle-block_annotate#10]
Looks like you have enabled travis-ci in your forked repo?
https://travis-ci.org/daniel-leon-gonzalez/moodle-plugin

but not for the main repo:
https://travis-ci.org/annotate-co/moodle-block_annotate

doing it for the main repo will give a number of advantages such as running automatically on pull requests etc.

**Comment by daniel-leon-gonzalez** [comment]
Thanks for your comment.

You are right, it should be fixed now. Sorry about that.

**Comment by danmarsden** [comment]
Great! - FYI - some plugin devs add the build passing image with link to travis into their README.md (which I think looks nice) - here's one of my plugins as an example:
https://github.com/danmarsden/moodle-mod_attendance/blob/master/README.md

here's the raw code for that file that prints the build image:
https://raw.githubusercontent.com/danmarsden/moodle-mod_attendance/master/README.md

**Comment by daniel-leon-gonzalez** [comment]
Thanks for the tip, Dan! It sounds like a good idea, I just added it.
