### ISSUE TITLE
blank page (no error)

### ISSUE THREAD

**Issue by danmarsden** [annotate-co/moodle-block_annotate#18]
I've set this up on a test system on my local machine (uses an internal IP) and I have not set up the web services user.

when clicking on the link to annotate from within my course I get redirected to the external annotate server but I get a blank page - I suspect this might occur as I am using an internal IP address which will be passed across but it would be good to improve the error reporting on the annotate server side when this occurs rather than showing the blank page (it does not redirect back to the local error page in the moodle plugin)

**Comment by daniel-leon-gonzalez** [comment]
Thanks for your comment - it should now be fixed and redirect back to the plugin error page.

As you said, the error is due to the use of an internal IP address, which prevents the annotate server from being able to fetch the file from Moodle.

**Comment by danmarsden** [comment]
great!
