### ISSUE TITLE
No English language strings available in AMOS for translating this plugin

### ISSUE THREAD

**Issue by germanvaleroelizondo** [annotate-co/moodle-block_annotate#22]
Hi,
I tried to translate this plugin in AMOS, but there are no English language strings there.

Can you please read the documentation for developers at
https://docs.moodle.org/dev/Translating_plugins#Plugins_with_coding_errors .

Thanks in advance for your help.

**Comment by daniel-leon-gonzalez** [comment]
Hi German,

Thank you for pointing it out and for the info provided. The language strings should now be available in AMOS.

Please let us know if there is anything else we can do.

**Comment by germanvaleroelizondo** [comment]
Hi,
The strings are now in AMOS. I have translated them into Mexican Spanish.
THANKS.

**Comment by daniel-leon-gonzalez** [comment]
Great, thank you very much!
