### ISSUE TITLE
$_GET should not be used in raw form

### ISSUE THREAD

**Issue by danmarsden** [annotate-co/moodle-block_annotate#6]
Please use optional/required_param functions with appropriate types to ensure $_GET does not include any malicious data/Javascript etc.
https://github.com/annotate-co/moodle-block_annotate/blob/d9a5f63de1073bd72069d9a75c3ae2106a0c96b9/annotate/error.php#L34

**Comment by daniel-leon-gonzalez** [comment]
Thanks for your comment, Dan. It should be fixed now.

**Comment by danmarsden** [comment]
great! - you should close this issue when you have fixed the related issue - you can sometimes be clever and include "fixes #1" in the commit message for the patch and github will automatically link to the commit and close the issue.
